//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesLibraryApi2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.GameDevelopers = new HashSet<GameDeveloper>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Gener { get; set; }
        public int NumberOfPlayers { get; set; }
        public Nullable<int> PublisherId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameDeveloper> GameDevelopers { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
